Revert "bottom: update to 0.11.1"
This reverts commit c99f8c91eaca41176897aa3c918038e2ae3636e5.

due to bottom requiring >= rust-1.88, rust is not upgradeable past 1.85.1 without llvm-19+

    error: rustc 1.85.1 is not supported by the following package:
      sysinfo@0.37.0 requires rustc 1.88